groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
    path('group/<slug>/publish/', views.group_publish, name='group_publish'),
    path('delete/<int:pk>/', views.SchoolDeleteView, name='group_delete'),
    path('drafts/', views.DraftListView.as_view(), name='draft_group'),
    
    
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('update/<int:pk>/',views.updatePost.as_view(),name='update'),
    
]

student_group_project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    
    
    path("students/", include("students.urls", namespace="students")),
    path("students/", include("django.contrib.auth.urls")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("posts/", include("posts.urls", namespace="posts")),
    
    path('admin/', admin.site.urls),
]

students/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'students'

urlpatterns = [
    path('login/', views.Login.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Student Group</title>

  

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>


  <body class="">
    <div class="col-12">
      <div class="row">
        <nav class="navbar navbar-expand-lg bg-dark mynav col-12" role="navigation" id="navbar">
          <div class="container ">
            <div class="navbar-nav align-items-center">
              <a class="navbar-brand mynav" href="{% url 'home' %}">STUDENT GROUP PROJECT</a>
            </div>
            <div class="navbar-nav ml-auto text-white">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
                <a class="nav-item nav-link" href="{% url 'groups:all' %}"  class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'groups:draft_group' %}"  class="btn btn-simple">Groups Draf List</a>
                <a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
                <a class="nav-item nav-link" href="{% url 'students:logout' %}" class="btn btn-simple">Log out</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'students:login' %}" class="btn btn-simple">Log in</a>
                <a class="nav-item nav-link" href="{% url 'students:signup' %}" class="btn btn-simple">Sign up</a>
              {% endif %}
            </div>
          </div>
        </nav>
    
        <div class="container mt-5">
          {% block content %}
    
          {% endblock %}
        </div>
      </div>

    </div> 


   

    <script src="{% static 'js/index.js'%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>

{% endblock %}